event_inherited();
playerXVelocityDefault = 12;
isShootObject = false;
PLAYERJUMPFORCE = -15;
is_carrying = false;
countJumps = 0;
sprPlayerStand = sYoungStand;
sprPlayerRun = sYoungRun;
sprPlayerJump = sYoungJump;
sprPlayerFall = sAdultJump;